### ISSUE TITLE
Score board simplification

### ISSUE THREAD

**Issue by mtfische** [Hk-tang/tictactoe#4]
I believe that the Losses row of the scoreboard is likely redundant. The player already knows that they have lost the same number as the other player as won.

https://github.com/Hk-tang/tictactoe/blob/16b142819a1b08499162160e6e96feb90ec6e792/src/main/java/cs/ualberta/cmput402/tictactoe/TicTacToeGame.java#L62-L65

**Comment by Hk-tang** [comment]
As the assignment specification says explicitly to " [keep] track of how many games were won, lost, tied by each player", I think we can leave the losses displayed.
