### ISSUE TITLE
Variable name clarification

### ISSUE THREAD

**Issue by mtfische** [Hk-tang/tictactoe#5]
The X,O,Draw score variables refer to games won and should be referred to as wins instead of scores.

https://github.com/Hk-tang/tictactoe/blob/16b142819a1b08499162160e6e96feb90ec6e792/src/main/java/cs/ualberta/cmput402/tictactoe/TicTacToeGame.java#L17-L19

**Comment by Hk-tang** [comment]
We also have "ties" and not "draws"

**Comment by forgeno** [comment]
Updated variable names for scores via commit: 9506206f070fa5a6f5d590812a1ff0e119e204e3
